services:
  app:
    build: .
    command: npm start
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:2.9.10
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "14268:14268" # Jaeger ingest
      - "3200:3200" # Tempo UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "9411:9411" # Zipkin
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    command: ["tempo", "-config.file=/etc/tempo.yaml"]
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-data:
